### ISSUE TITLE
Still missing: IO argument

### ISSUE THREAD

**Issue by timholy** [zelunw/DemoPackageZW.jl#3]
A PR adding an IO argument is all that's left. This is trickier because #2 is already merged, and part of the challenge of this assignment was to resolve a merge conflict. You can still generate one:

1. In your "Git History" tab from the "Source control" view, create a new branch starting from 3b2482cddb5d9767daa1dd334f710fe06c653e0e (this is before that PR merged)
2. Add the io argument as instructed in the homework.
3. Submit the PR.
4. Resolve the merge conflict, either in the web interface or (better, for your learning) locally in VS Code ("merge" the `main` branch into your new branch)
5. update the PR & merge.

**Comment by zelunw** [comment]
I think this worked. Will try the "Fixes #X" trick for the next issue
